안녕하세요. 수강생 여러분~! Chapter21 ~ 32 수업은 잘 들으셨나요?

Chapter21 ~ 32의 수업 내용을 바탕으로 아래 문제를 풀어주시면 됩니다.


<br>


[**답변 입력 방법**]

문제 아래에 있는 코드 입력창에 정답코드를 작성하신 후  __▷ 버튼을 클릭해 코드를 실행__ 해보세요<br>

---

[문제 1]
사용자로부터 이름과 나이를 입력 받아, "안녕하세요, [이름]님! 당신은 [나이]살입니다."라고 출력하는 함수 greet_user를 작성하세요.

In [35]:
def greet_user():

    name = input("이름: ")

    age = input("나이: ")

    print(f"안녕하세요, {name}님! 당신은 {age}살입니다.")

---

[문제 2] 여러 숫자를 입력받아 그 합계를 반환하는 함수 sum_numbers를 작성하세요. 이 때, 가변 매개변수를 사용하세요.

In [36]:
def sum_numbers(*numbers):
    return sum(numbers)

result = sum_numbers(10, 20, 30)
print("합계:", result)

합계: 60

---

[문제 3] 사용자의 이름을 출력하는 함수 print_name을 작성하세요. 만약 이름이 주어지지 않았다면, 기본값으로 "익명"을 사용하세요.

In [37]:
def print_name(name="익명"):
    print(name)

print_name()

익명

---

[문제 4] 사용자의 이름, 나이, 성별을 출력하는 함수 print_info를 작성하세요. 이 때, 모든 매개변수는 키워드 매개변수로만 받도록 하세요.

In [39]:
def print_info(*, name, age, gender):
    print(f"이름: {name}")
    print(f"나이: {age}")
    print(f"성별: {gender}")

print_info(name="name", age="age", gender="gender")

이름: name
나이: age
성별: gender

---

[문제 5] 두 개의 정수를 받아 합을 반환하는 함수 add를 작성하세요. 매개변수와 반환값에 타입 어노테이션을 추가하세요.

In [48]:
def add(a: int, b: int) -> int:
    return a + b
    result = add(10, 20)

print("합:", result)

합: 30

---

[문제 6] 0부터 시작하여 n까지의 숫자 중에서 홀수만 생성하는 제너레이터 odd_numbers를 작성하세요.

In [61]:
def odd_numbers(n):
    for i in range(n):
        if i % 2 != 0:
            yield i

for num in odd_numbers(10):
    print(num)

1
3
5
7
9

---

[문제 7] 두 숫자를 더하는 람다 함수를 작성하고, 이를 변수에 할당한 후 사용하세요.

In [20]:
add = lambda a, b: a + b

# 사용
result = add(10, 20)
print("합:", result)

합: 30

---

[문제 8] 사용자로부터 3개의 숫자를 입력받아, 이를 튜플로 만든 후 최소값과 최대값을 출력하는 함수 min_max를 작성하세요.

In [65]:
def min_max():
    a = int(input("7: "))
    b = int(input("3: "))
    c = int(input("10: "))

    numbers = (a, b, c)

    print(f"입력한 값: {numbers}")
    print(f"최소값: {min(numbers)}")
    print(f"최대값: {max(numbers)}")    #???????????????

---

[문제 9] 주어진 숫자가 짝수인지 확인하는 함수 is_even을 작성하세요. 짝수라면 True를, 아니라면 False를 반환하세요. 함수 내에서 조기 리턴을 활용하세요.

In [24]:
def is_even(number):
    if number % 2 == 0:
        return True
    return False

print(is_even(4))
print(is_even(7))

True
False

---

[문제 10] 팩토리얼을 계산하는 재귀 함수 factorial을 작성하세요.

In [26]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

print(factorial(5))

120

---

[문제 11] 문자열 리스트를 받아, 각 문자열의 길이를 출력하는 함수 print_lengths를 작성하세요.

In [28]:
def print_lengths(strings):
    for s in strings:
        print(f"'{s}'의 길이: {len(s)}")

print_lengths(["apple", "banana", "kiwi"])

'apple'의 길이: 5
'banana'의 길이: 6
'kiwi'의 길이: 4

---

[문제 12] 두 문자열을 받아서 긴 문자열을 반환하는 함수 longer_string을 작성하세요. 만약 두 문자열의 길이가 같다면, 첫 번째 문자열을 반환하세요.

In [32]:
def longer_string(str1, str2):
    if len(str1) > len(str2):
        return str1
    elif len(str2) > len(str1):
        return str2
    else:
        return str1

print(longer_string("hello", "world!"))
print(longer_string("python", "coding"))

world!
python